// Generated by CoffeeScript 1.7.1
(function() {
  var async, fs, nib, path, stylus,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  stylus = require('stylus');

  nib = require('nib');

  path = require('path');

  async = require('async');

  fs = require('fs');

  module.exports = function(env, callback) {
    var StylusPlugin;
    StylusPlugin = (function(_super) {
      __extends(StylusPlugin, _super);

      function StylusPlugin(_filepath, _text) {
        this._filepath = _filepath;
        this._text = _text;
      }

      StylusPlugin.prototype.getFilename = function() {
        return this._filepath.relative.replace(/styl$/, 'css');
      };

      StylusPlugin.prototype.getView = function() {
        return function(env, locals, contents, templates, callback) {
          var error, options;
          try {
            options = env.config.stylus || {};
            options.filename = this.getFilename();
            options.paths = [path.dirname(this._filepath.full)];
            return stylus(this._text, options).use(nib()).render(function(err, css) {
              if (err) {
                return callback(err);
              } else {
                return callback(null, new Buffer(css));
              }
            });
          } catch (_error) {
            error = _error;
            return callback(error);
          }
        };
      };

      return StylusPlugin;

    })(env.ContentPlugin);
    StylusPlugin.fromFile = function(filepath, callback) {
      return fs.readFile(filepath.full, function(error, buffer) {
        if (error) {
          return callback(error);
        } else {
          return callback(null, new StylusPlugin(filepath, buffer.toString()));
        }
      });
    };
    env.registerContentPlugin('styles', '**/*.styl', StylusPlugin);
    return callback();
  };

}).call(this);
